### PR TITLE
Enabling translations for Windows installer. Fixed permissions

### PR DESCRIPTION
**Pull request by Hou5e**
Enabling translations for Windows installer. The additional ANSI plugins were removed and replaced with the Unicode versions of them.

Plugin: FindProcDLL.dll (2009-11-12) {not working} was replaced with this one with Unicode support:
nsProcess.nsh & nsProcess.dll (2011-06-28) https://nsis.sourceforge.io/NsProcess_plugin
It doesn't have 'WaitProcEnd', so that is just done in script code.

Fixed permissions on the All Users Program Data folder. The order for these 2 commands needed to be swapped:
  ; Set working directory for shortcuts, etc. Do before AccessControl::GrantOnFile
  SetOutPath $DataDir
  AccessControl::GrantOnFile "$DataDir" "(S-1-5-32-545)" "FullAccess"

### CODE REVIEW

**Comment by jcoffland** [comment]
This looks great.  Thank you!  The license and custom page translation would be great if you have the energy for it.  I'll wait to merge this until you tell me you're done making changes.

**Comment by kbernhagen** [comment]
`  nsExec::Exec '"$INSTDIR\${CLIENT_EXE}" --send-command=shutdown'`
is only valid for v7 FAHClient.exe

**Comment by jcoffland** [comment]
Thanks!

**Comment by jcoffland** [comment]
Note my changes here: https://github.com/FoldingAtHome/fah-client-bastet/commit/d6b1313a1bb1ea0dac25c5624cf1b013f160f688.  I want to avoid code repetition.  DRY principal.

**Pull request merged**
