### PR TITLE
RPM package revival

### PR DESCRIPTION
**Pull request by marcosfrm**
WIP. Changes needed in the SPEC generation code:

- `Summary:` generally does not contain version information
- `Name:` should be `fah-client` rather than `fah_client`
- `License:` is now `GPLv3`
- Not sure if `Prefix:` is useful, can stay I think
- Need more requires now:

```
%if 0%{?el7}
BuildRequires:     systemd
%else
BuildRequires:     systemd-rpm-macros
%endif
Requires(pre):     systemd shadow-utils
Requires(post):    systemd
Requires(preun):   systemd
Requires(postun):  systemd
```

And:

```
Conflicts: fahclient
Obsoletes: fahclient
```

- Build system needs to replace `%(PACKAGE_URL)s` in `install/rpm/post.in` -> `install/rpm/post`
- Copy `install/lin/fah-client.service` and list it in the `%files` section

For v8 RPM I propose a new approach to `/var/lib/fah-client` and `/var/log/fah-client` directories. Instead of creating them in post install scripts, make the package itself own them. SPEC will look like:

```
%files
%doc /usr/share/doc/fah-client/README.md
%doc /usr/share/doc/fah-client/CHANGELOG.md
%doc /usr/share/doc/fah-client/LICENSE
%attr(0775,root,root) /usr/bin/fah-client
/usr/share/applications/fah-client.desktop
/usr/share/pixmaps/fahlogo.icns
/usr/share/pixmaps/fahlogo.png
%attr(-,fah-client,fah-client) %dir /var/lib/fah-client
%attr(-,fah-client,fah-client) %dir /var/log/fah-client
```
(dropped redundant `%defattr(- root root)`)

`fah-client` user is created at `%pre` section. RPM will create both and change ownership/permission. On unistall, it will try to remove the directories only. If they are populated, nothing is done. _purge-like_ behaviour can be added in `%preun`, removing their contents on uninstall (`$1 -eq 0`) -- and in `%postun` for user/group removal.

v7 configuration migration is based on https://github.com/FoldingAtHome/fah-client-bastet/pull/152.

### CODE REVIEW

**Comment by kbernhagen** [comment]
Note: I believe the current rpm files were imported without modification from v7.

`install` `*.in` files were added recently and are currently processed in `SConstruct` before the packager code runs. Processed files end up in `./build/install/rpm`.

**Comment by kbernhagen** [comment]
I think the rpm section in `SConstruct` packager args might be
```
        rpm_license        = env['PACKAGE_LICENSE'],
        rpm_group          = 'Applications/Internet',
        rpm_requires       = 'systemd, expat, bzip2-libs',
        rpm_build          = 'build/install/rpm/build',
        rpm_post           = 'build/install/rpm/post',
        rpm_preun          = 'build/install/rpm/preun',
        rpm_conflicts      = 'FAHClient, fahclient',
        rpm_obsoletes      = 'FAHClient, fahclient',
        rpm_build_requires = 'systemd',
        rpm_pre_requires   = 'systemd, shadow-utils',
        rpm_post_requires  = 'systemd',
        rpm_preun_requires = 'systemd',
        rpm_postun_requires= 'systemd',
```

The `cbang` rpm script would need some changes.
Need to add support for `misc` or `systemd` and some `rpm_*_requires` vars.

**Comment by kbernhagen** [comment]
I think I only appended version to `summary` for the benefit of the macOS package title.
I can modify the macOS packager scripts to append version if it is missing.

**Comment by kbernhagen** [comment]
I think `*.icns` files are only for macOS.
I don't know why `fahlogo.icns` is included.

**Comment by marcosfrm** [comment]
Ok, before adapting `SConstruct`...

cbang:

```diff
diff --git a/config/rpm/__init__.py b/config/rpm/__init__.py
index ea373240..98c14982 100644
--- a/config/rpm/__init__.py
+++ b/config/rpm/__init__.py
@@ -68,8 +68,10 @@ def build_function(target, source, env):
         write_var(env, f, 'Conflicts', 'rpm_conflicts', multi = True)
         write_var(env, f, 'Obsoletes', 'rpm_obsoletes', multi = True)
         write_var(env, f, 'BuildRequires', 'rpm_build_requires', multi = True)
-        write_var(env, f, 'Requires(pre)', 'rpm_pre_requires', multi = True)
         write_var(env, f, 'Requires', 'rpm_requires', multi = True)
+        write_var(env, f, 'Requires(pre)', 'rpm_pre_requires', multi = True)
+        write_var(env, f, 'Requires(preun)', 'rpm_preun_requires', multi = True)
+        write_var(env, f, 'Requires(post)', 'rpm_post_requires', multi = True)
         write_var(env, f, 'Requires(postun)', 'rpm_postun_requires',
                   multi = True)
 
@@ -87,18 +89,18 @@ def build_function(target, source, env):
         if 'rpm_filelist' in env:
             f.write('%%files -f %s\n' % env.get('rpm_filelist'))
         else: f.write('%files\n')
-        f.write('%defattr(- root root)\n')
 
         for files in [
             ['documents', '/usr/share/doc/' + name, '%doc', None],
-            ['programs', '/usr/bin', '%attr(0775 root root)', 0o755],
-            ['scripts', '/usr/bin', '%attr(0775 root root)', 0o755],
+            ['programs', '/usr/bin', '%attr(0775,-,-)', 0o755],
+            ['scripts', '/usr/bin', '%attr(0775,-,-)', 0o755],
             ['desktop_menu', '/usr/share/applications', None, None],
-            ['init_d', '/etc/init.d', '%config %attr(0775 root root)', None],
+            ['init_d', '/etc/init.d', '%config %attr(0775,-,-)', None],
             ['config', '/etc/' + name, '%config', None],
             ['icons', '/usr/share/pixmaps', None, None],
             ['mime', '/usr/share/mime/packages', None, None],
             ['platform_independent', '/usr/share/' + name, None, None],
+            ['misc', '/usr', None, None], # XXX: /usr/lib in Fedora and RHEL
             ]:
             install_files(f, env, files[0], build_dir, files[1], files[2],
                           files[3])
```

How make it create directories and list them prefixed with `%attr(-,fah-client,fah-client) %dir` in the `%files` section? Need help with Python... :(

**Comment by marcosfrm** [comment]
`SConstruct` is replacing not only `%(PACKAGE_URL)s`, but `%systemd_post fah-client.service` too with:

```
<SCons.Script.SConscript.SConsEnvironment object at 0x7fc5f6b5d040>ystemd_post fah-client.service
```

**Comment by kbernhagen** [comment]
I think your line for misc is wrong. The entire destination is passed in the list of
lists in SConstruct.

**Comment by kbernhagen** [comment]
On my Ubuntu vm, I think /lib is a symlink to /usr/lib

**Comment by kbernhagen** [comment]
Rather than use misc, it might be better to add a ‘systemd’ key, similar to the ’init_d’ key.

**Comment by marcosfrm** [comment]
Attempt to make cbang's `rpmbuild` process less convoluted:

```diff
diff --git a/config/rpm/__init__.py b/config/rpm/__init__.py
index ea373240..67a7fd00 100644
--- a/config/rpm/__init__.py
+++ b/config/rpm/__init__.py
@@ -42,18 +42,23 @@ def install_files(f, env, key, build_dir, path, prefix = None, perms = None,
 def build_function(target, source, env):
     name = env.get('package_name_lower')

-    # Create package build dir
-    build_dir = 'build/%s-RPM' % name
-    if os.path.exists(build_dir): shutil.rmtree(build_dir)
-    os.makedirs(build_dir)
+    # Create directories needed by rpmbuild
+    for dir in ['BUILD', 'BUILDROOT', 'RPMS', 'SOURCES', 'SPECS', 'SRPMS']:
+        rpmdir = 'build/' + dir
+        if os.path.exists(rpmdir): shutil.rmtree(rpmdir)
+        os.makedirs(rpmdir)
+
+    # SPEC's %install section is responsible for populating BUILDROOT
+    # (aka %{buildroot} or $RPM_BUILD_ROOT)
+    build_dir = 'build/BUILD'

     # Create the SPEC file
-    spec_file = 'build/%s.spec' % name
+    spec_file = 'build/SPECS/%s.spec' % name
     with open(spec_file, 'w') as f:
         # Create the preamble
         write_var = env.WriteVariable
         write_var(env, f, 'Summary', 'summary')
-        write_var(env, f, 'Name', 'package_name_lower', None, replace_dash)
+        write_var(env, f, 'Name', 'package_name_lower')
         write_var(env, f, 'Version', 'version', None, replace_dash)
         write_var(env, f, 'Release', 'package_build', '1', replace_dash)
         write_var(env, f, 'License', 'rpm_license')
@@ -68,16 +73,16 @@ def build_function(target, source, env):
         write_var(env, f, 'Conflicts', 'rpm_conflicts', multi = True)
         write_var(env, f, 'Obsoletes', 'rpm_obsoletes', multi = True)
         write_var(env, f, 'BuildRequires', 'rpm_build_requires', multi = True)
-        write_var(env, f, 'Requires(pre)', 'rpm_pre_requires', multi = True)
         write_var(env, f, 'Requires', 'rpm_requires', multi = True)
+        write_var(env, f, 'Requires(pre)', 'rpm_pre_requires', multi = True)
+        write_var(env, f, 'Requires(preun)', 'rpm_preun_requires', multi = True)
+        write_var(env, f, 'Requires(post)', 'rpm_post_requires', multi = True)
         write_var(env, f, 'Requires(postun)', 'rpm_postun_requires',
                   multi = True)

         # Description
         write_spec_text_section(f, env, 'description', 'description')

-        f.write('%define strip ' + env.get('STRIP', 'strip') + '\n\n')
-
         # Scripts
         for script in ['prep', 'build', 'install', 'clean', 'pre', 'post',
                        'preun', 'postun', 'verifyscript']:
@@ -87,18 +92,18 @@ def build_function(target, source, env):
         if 'rpm_filelist' in env:
             f.write('%%files -f %s\n' % env.get('rpm_filelist'))
         else: f.write('%files\n')
-        f.write('%defattr(- root root)\n')

         for files in [
             ['documents', '/usr/share/doc/' + name, '%doc', None],
-            ['programs', '/usr/bin', '%attr(0775 root root)', 0o755],
-            ['scripts', '/usr/bin', '%attr(0775 root root)', 0o755],
+            ['programs', '/usr/bin', '%attr(0775,-,-)', 0o755],
+            ['scripts', '/usr/bin', '%attr(0775,-,-)', 0o755],
             ['desktop_menu', '/usr/share/applications', None, None],
-            ['init_d', '/etc/init.d', '%config %attr(0775 root root)', None],
+            ['init_d', '/etc/init.d', '%config %attr(0775,-,-)', None],
             ['config', '/etc/' + name, '%config', None],
             ['icons', '/usr/share/pixmaps', None, None],
             ['mime', '/usr/share/mime/packages', None, None],
             ['platform_independent', '/usr/share/' + name, None, None],
+            ['misc', '/', None, None],
             ]:
             install_files(f, env, files[0], build_dir, files[1], files[2],
                           files[3])
@@ -106,22 +111,14 @@ def build_function(target, source, env):
         # ChangeLog
         write_spec_text_section(f, env, 'changelog', 'rpm_changelog')

-    # Create directories needed by rpmbuild
-    for dir in ['BUILD', 'BUILDROOT', 'RPMS', 'SOURCES', 'SPECS', 'SRPMS']:
-        dir = 'build/' + dir
-        if not os.path.exists(dir): os.makedirs(dir)
-
-
     # Build the package
-    build_dir = os.path.realpath(build_dir)
-    cmd = 'rpmbuild -bb --buildroot %s --define "_topdir %s/build" ' \
-        '--target %s %s' % (
-        build_dir, os.getcwd(), env.GetPackageArch(), spec_file)
-    CommandAction(cmd).execute(target, [build_dir], env)
+    target = str(target[0])
+    cmd = 'rpmbuild -bb --define "_topdir %s/build" --define "_rpmfilename %s" ' \
+          '--target %s %s' % (os.getcwd(), target, env.GetPackageArch(), spec_file)
+    CommandAction(cmd).execute(target, [], env)

     # Move the package
-    target = str(target[0])
-    path = 'build/RPMS/' + env.GetPackageArch() + '/' + target
+    path = 'build/RPMS/' + target
     shutil.move(path, target)

```

Two pending things:

- RPM filename still has underscores
- Need a way to create directories (`%attr(-,fah-client,fah-client) %dir` in the `%files` section)

I am like https://i.imgflip.com/ry4bq.jpg ...

**Comment by kbernhagen** [comment]
For `cbang/config/rpm`, might something like this be correct?
```
            ['systemd', '/usr/lib/systemd/system', '%config %attr(0644,-,-)', None],
```
Then `cbang/config/deb` might have
```
    install_files(env, 'systemd', build_dir + '/lib/systemd/system', 0o644)
```
I could easily be mangling this.

**Comment by kbernhagen** [comment]
- Need a way to create directories (%attr(-,fah-client,fah-client) %dir in the %files section)

Maybe create directories like this?
```
            ['client_dirs', '/', '%attr(-,fah-client,fah-client) %dir', 0o755],
```

**Comment by kbernhagen** [comment]
- RPM filename still has underscores

This is probably caused by `cbang/config/packager`

**Comment by marcosfrm** [comment]
With https://github.com/CauldronDevelopmentLLC/cbang/pull/125, a functional RPM is created.

I kept `BuildRequires: systemd` instead of `systemd-rpm-macros` because I think CentOS 7 is an ideal build system for now. It is the oldest still maintained RHEL-based distribution with systemd. The resulting binary shall work on any later Fedora/RHEL-like version. I need to install CentOS 7 on a VM to give it a test though.

Removed `expat` and `bzip2-libs` dependencies because rpmbuild will auto add library deps:

```
Requires: ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.16)(64bit) libc.so.6(GLIBC_2.17)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.2)(64bit) libc.so.6(GLIBC_2.32)(64bit) libc.so.6(GLIBC_2.33)(64bit) libc.so.6(GLIBC_2.34)(64bit) libc.so.6(GLIBC_2.4)(64bit) libc.so.6(GLIBC_2.7)(64bit) libc.so.6(GLIBC_2.8)(64bit) libc.so.6(GLIBC_2.9)(64bit) libcrypto.so.3()(64bit) libcrypto.so.3(OPENSSL_3.0.0)(64bit) libm.so.6()(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libssl.so.3()(64bit) libssl.so.3(OPENSSL_3.0.0)(64bit) rtld(GNU_HASH)
```
(CentOS Stream 9 machine)

Removing "Draft" status now, but more testing still needed!

**Comment by kbernhagen** [comment]
The deb build is on debian-10.
An rpm build machine has not been set up or defined yet for v8.
Isn't CentOS deprecated?

**Comment by kbernhagen** [comment]
I am working on an osx packager update.
Once done and merged, version can be removed from summary.
I can do it, because I will also be changing the distpkg_ variable name prefix.

**Comment by marcosfrm** [comment]
> The deb build is on debian-10. An rpm build machine has not been set up or defined yet for v8. Isn't CentOS deprecated?

Debian 10 is its oldest still maintained version. Like CentOS 7 is for RHEL/Fedora world.

"Regular" CentOS is EOL starting with version 8. They replaced it with "CentOS Stream", which is not exactly the same product. Version 7, on the other hand, is still supported until june 30, 2024:

https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

CentOS Stream has shorter life cycle compared to RHEL. There are other clones now, but "bug-for-bug compatibility" is gone:

https://almalinux.org/blog/future-of-almalinux/

**Comment by kbernhagen** [comment]
Interesting.
Joseph would have to comment, but I believe many libraries are statically linked in the client. I don’t know if that could be a problem building on CentOS 7.

**Comment by kbernhagen** [comment]
The build support is still in a private repo. 
mid you’re interested, this is pretty much the same:
https://github.com/CauldronDevelopmentLLC/CAMotics/tree/master/buildbot

**Comment by marcosfrm** [comment]
Forgot to mention this PR depends on https://github.com/FoldingAtHome/fah-client-bastet/pull/152 (`--config=/etc/fah-client/config.xml` in `install/lin/fah-client.service`).

**Pull request merged**
