### PR TITLE
Use atomic bools

### PR DESCRIPTION
**Pull request by kbernhagen**

### CODE REVIEW

**Comment by jcoffland** [comment]
I was thinking about this and I'm not convinced that ``std::atomic<bool>`` is ever necessary.  A bool value can only ever be true or false.  There's no way for it to be partially updated.  Therefore, bools are always atomic.

**Comment by jcoffland** [comment]
I there can be issues with the compiler reordering operations which I believe ``std::atomic`` prevents.  So if you have code that expect that something has happened before the bool is changed you could have problems.  E.g. something like this:

```c++
copy_data();
dataCopied = true;

. . .

if (dataCopied) use_data();
```

In which case ``std::atomic<bool>`` would be useful but I don't think we've have those issues here.

It maybe a bit pedantic but I'll accept the PR.

**Comment by kbernhagen** [comment]
I thought it also guarantees immediate thread synchronization.

**Comment by kbernhagen** [comment]
If a bool is 8 bits, I don’t think it is inherently atomic unless int is also 8 bits. I think an atomic bool is the cpu word size.

**Comment by jcoffland** [comment]
A bool is either false and equal to 0 or not, regardless of how it's stored.  It can't be in an inconsistent state.  But, operations on one thread can appear to happen out of order from the perspective of another thread due to operation reordering that happens in modern CPUs.  "Thread synchronization", as you put it or memory barriers to put it another way prevent this.  So there are reasons to use ``std::atomic<bool>``.  Still, I don't believe it affects this code.

**Comment by kbernhagen** [comment]
I agree it hasn't mattered in the code.

My understanding is that a cpu can only store a value in one operation if it is word-aligned and either word-sized or padded to word size.

**Pull request merged**
